---
title: "Homework 3"
subtitle: "Part 3"
output: github_document
author: Ronae McLin rkm2147
---

```{r}


library(wesanderson)
wes_palette("GrandBudapest2")

```


```{r}
library(tidyverse)
library(patchwork)
library(ggridges)
library(wesanderson)


knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)
theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "GrandBudapest2",
  ggplot2.continuous.fill = "GrandBudapest2"
)

scale_colour_discrete = scale_color_viridis_d

scale_fill_discrete = scale_fill_viridis_d
```

don't forget to load this
```{r}
library(rvest)
library(httr)
```

## scrape a table

i want the first table 

```{r}
url = "http://samhda.s3-us-gov-west-1.amazonaws.com/s3fs-public/field-uploads/2k15StateFiles/NSDUHsaeShortTermCHG2015.htm"
```

```{r}
drug_use_html = read_html(url)
```

extract tables

```{r}
```


```{r}
tabl_marj = 
drug_use_html %>% 
  html_nodes(css = "table") %>% 
  first() %>% 
  html_table() %>%  
  slice(-1) %>% 
  as_tibble()

```

